"""After Effects .jsx export: solved camera + anchor nulls + overlay comp.

Running the script inside After Effects builds a comp at the footage
resolution, a 3D camera keyframed from the solve, and a null for every
overlay anchor so the artist can parent broadcast graphics straight onto the
tracked points.  The footage itself is never transformed (section 31).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Sequence

from ..camera import CameraTrack
from ..overlay import OverlayElement
from ..spec import HoleSpec

_HEADER = """// Generated by matchmove - GOLF COURSE DRONE MATCH MOVE
// Master prompt v1.0. The solved camera below describes the ORIGINAL drone
// move. Do not retime, restabilise or reframe the footage (section 31).
"""


def _ae_position(x: float, y: float, z: float):
    """ENU (Z up, metres) -> AE world (Y down, centimetres)."""
    return [x * 100.0, -z * 100.0, y * 100.0]


def export_after_effects_jsx(
    path: str | Path,
    track: CameraTrack,
    elements: Sequence[OverlayElement],
    spec: HoleSpec,
    comp_name: str = "",
) -> Path:
    first, last = track.frame_range
    fps = track.fps
    intr = track.intrinsics
    comp_name = comp_name or f"{spec.course_name}_H{spec.hole_number:02d}_MATCHMOVE"

    keys = []
    for k in track.keyframes:
        keys.append({
            "t": k.frame / fps,
            "p": _ae_position(*k.pose.position.as_tuple()),
            "yaw": k.pose.yaw,
            "pitch": k.pose.pitch,
            "roll": k.pose.roll,
            "zoom": (k.focal_px or intr.focal_px),
        })

    nulls = []
    for e in elements:
        if e.anchor is None:
            continue
        nulls.append({
            "name": f"{e.kind.value}_{e.id}"[:60],
            "p": _ae_position(*e.anchor.as_tuple()),
            "label": e.label,
        })

    body = f"""{_HEADER}
(function () {{
  var W = {intr.width}, H = {intr.height}, FPS = {fps};
  var DUR = {max(1, last - first + 1)} / FPS;
  var proj = app.project || app.newProject();
  app.beginUndoGroup("matchmove import");
  var comp = proj.items.addComp({json.dumps(comp_name)}, W, H, 1.0, DUR, FPS);

  var cam = comp.layers.addCamera("SOLVED_DRONE_CAM", [W / 2, H / 2]);
  cam.property("Zoom").setValue({intr.focal_px:.4f});
  var keys = {json.dumps(keys, indent=2)};
  var pos = cam.property("Position");
  var ori = cam.property("Orientation");
  var zoom = cam.property("Zoom");
  cam.property("Auto-Orient").setValue(AutoOrientType.NO_AUTO_ORIENT);
  for (var i = 0; i < keys.length; i++) {{
    var k = keys[i];
    pos.setValueAtTime(k.t, k.p);
    // AE orientation: X = pitch down-positive, Y = yaw, Z = roll
    ori.setValueAtTime(k.t, [-k.pitch, k.yaw, k.roll]);
    zoom.setValueAtTime(k.t, k.zoom);
  }}

  var nulls = {json.dumps(nulls, indent=2)};
  for (var j = 0; j < nulls.length; j++) {{
    var n = comp.layers.addNull(DUR);
    n.threeDLayer = true;
    n.name = nulls[j].name;
    n.property("Position").setValue(nulls[j].p);
    n.comment = nulls[j].label;
  }}

  app.endUndoGroup();
  alert("matchmove: imported solved camera + " + nulls.length + " tracked anchors.");
}})();
"""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding="utf-8")
    return p
