"""Blender .py export: solved camera, anchor empties and course feature curves.

Run with ``blender --python <file>`` or paste into the scripting workspace.
Builds the hole in real metres so the AR geometry can be laid out in 3D and
rendered over the plate.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Sequence

from ..camera import CameraTrack
from ..overlay import OverlayElement
from ..spec import HoleSpec


def export_blender_py(
    path: str | Path,
    track: CameraTrack,
    elements: Sequence[OverlayElement],
    spec: HoleSpec,
) -> Path:
    intr = track.intrinsics
    keys = [
        {
            "f": k.frame,
            "p": list(k.pose.position.as_tuple()),
            "ypr": [k.pose.yaw, k.pose.pitch, k.pose.roll],
            "focal_px": k.focal_px or intr.focal_px,
        }
        for k in track.keyframes
    ]
    curves = [
        {
            "name": f"{e.kind.value}_{e.id}",
            "points": [list(p.as_tuple()) for p in e.points],
            "closed": e.closed,
            "label": e.label,
        }
        for e in elements if len(e.points) >= 2
    ]
    anchors = [
        {"name": f"{e.kind.value}_{e.id}", "p": list(e.anchor.as_tuple()), "label": e.label}
        for e in elements if e.anchor is not None
    ]

    body = f'''"""Generated by matchmove - GOLF COURSE DRONE MATCH MOVE (master prompt v1.0).

Units are metres in the hole's local ENU frame; the origin is the GREEN CENTER.
The camera animation below is the ORIGINAL drone move recovered from the
footage - do not alter it (section 31).
"""

import math
import bpy

FPS = {track.fps}
WIDTH, HEIGHT = {intr.width}, {intr.height}
SENSOR_W = 36.0  # arbitrary sensor; focal is derived to match the solved FOV
KEYS = {json.dumps(keys, indent=4)}
ANCHORS = {json.dumps(anchors, indent=4)}
CURVES = {json.dumps(curves, indent=4)}


def ypr_to_euler(yaw, pitch, roll):
    """Drone yaw/pitch/roll -> Blender camera XYZ euler (camera looks down -Z)."""
    return (
        math.radians(90.0 + pitch),
        math.radians(roll),
        math.radians(-yaw),
    )


def build():
    scene = bpy.context.scene
    scene.render.fps = int(round(FPS))
    scene.render.resolution_x = WIDTH
    scene.render.resolution_y = HEIGHT
    scene.frame_start = KEYS[0]["f"]
    scene.frame_end = KEYS[-1]["f"]

    cam_data = bpy.data.cameras.new("SOLVED_DRONE_CAM")
    cam_data.sensor_width = SENSOR_W
    cam = bpy.data.objects.new("SOLVED_DRONE_CAM", cam_data)
    scene.collection.objects.link(cam)
    scene.camera = cam
    cam.rotation_mode = "XYZ"

    for k in KEYS:
        cam.location = k["p"]
        cam.rotation_euler = ypr_to_euler(*k["ypr"])
        cam_data.lens = k["focal_px"] * SENSOR_W / WIDTH
        cam.keyframe_insert("location", frame=k["f"])
        cam.keyframe_insert("rotation_euler", frame=k["f"])
        cam_data.keyframe_insert("lens", frame=k["f"])

    for a in ANCHORS:
        e = bpy.data.objects.new(a["name"], None)
        e.empty_display_type = "PLAIN_AXES"
        e.empty_display_size = 2.0
        e.location = a["p"]
        scene.collection.objects.link(e)

    for c in CURVES:
        cu = bpy.data.curves.new(c["name"], "CURVE")
        cu.dimensions = "3D"
        spline = cu.splines.new("POLY")
        pts = c["points"]
        spline.points.add(len(pts) - 1)
        for i, p in enumerate(pts):
            spline.points[i].co = (p[0], p[1], p[2], 1.0)
        spline.use_cyclic_u = bool(c["closed"])
        ob = bpy.data.objects.new(c["name"], cu)
        scene.collection.objects.link(ob)


if __name__ == "__main__":
    build()
'''
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(body, encoding="utf-8")
    return p
